blank_issues_enabled: false
contact_links:
  - name: Home Assistant Community forum
    url: https://community.home-assistant.io/t/sagemcom-router-support/179880/last
    about: Please ask and answer questions here.