default_config:

logger:
  default: error
  logs:
    custom_components.sagemcom_fast: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:
